### PR TITLE
Fixes #127 and 93e087ecd7ebf0fa3e.

### PR DESCRIPTION
**Pull request by shhyou**

### CODE REVIEW

**Comment by rfindler** [comment]
Does the `test-execute` parameter ever actually get a value that's a boolean?

**Comment by shhyou** [comment]
Yes, as set by the Test Engine plugin
https://github.com/racket/htdp/blob/93e087ecd7ebf0fa3ee9ea90caff418d7e1e9df1/htdp-lib/test-engine/test-tool.rkt#L135-L144

**Comment by rfindler** [comment]
Oops! I meant _not_ a boolean. (I'm asking about the comment change that's in the diff in the PR.)

**Comment by shhyou** [comment]
If the Test Engine plugin is not loaded, the exception handler will pass `'uninstalled` to `test-on?`. It then flows into `test-execute`.
https://github.com/racket/htdp/blob/93e087ecd7ebf0fa3ee9ea90caff418d7e1e9df1/htdp-lib/lang/htdp-langs.rkt#L172-L182

**Comment by shhyou** [comment]
Or maybe L177 should become `(test-execute (and tests-on? #t))`?

**Comment by rfindler** [comment]
Oh, of course. Silly me. Yes, I think it is safer to be `(and tests-on? #t)`

**Comment by rfindler** [comment]
Thanks!

**Pull request merged**
