### PR TITLE
fix quotient description

### PR DESCRIPTION
**Pull request by Fil0sOFF**
The arguments seem to be mixed up in the description of "quotient" function

### CODE REVIEW

**Comment by mfelleisen** [comment]
The [dictionary](https://www.macmillandictionary.com/us/dictionary/american/divide-into) says this fix is wrong

**Comment by mflatt** [comment]
FWIW, I think "divide by" is more common than "divide into", maybe because "divide by" matches the traditional ➗ order.

**Comment by jbclements** [comment]
I agree that the proposed fix is wrong, but I do see problems with the original text, in that it contains the phrase "divides the second", suggesting that the second one is split into pieces, when in fact it's the first. Can I instead suggest the following:

Divides the first integer---also called the dividend---by the second---known as 
the divisor---to obtain the @index[(list "divide" "quotient")]{quotient}.

... or just leave it alone, I suppose.

**Comment by jbclements** [comment]
In case it's not obvious, I think I'm basically hanging some words on Matthew's suggestion.

**Comment by mfelleisen** [comment]
Replaced by 86ad0743..c216bdf6

**Pull request closed without merging**
