### PR TITLE
Added beginner-= that requires at least two arguments.

### PR DESCRIPTION
**Pull request by maueroats**

### CODE REVIEW

**Comment by maueroats** [comment]
A semi-common error is forgetting the second item to compare for equality, which is then unexpectedly true.

**Comment by mfelleisen** [comment]
It looks straightforward. But do you want to add a test to `htdp/htdp-test/tests/htdp-lang/beginner.rkt` to make sure you get the error message for `(= 42)` that you want?

**Comment by maueroats** [comment]
If it were up to me, I would keep this feature in beginner and intermediate.
According to the [docs](https://docs.racket-lang.org/htdp-langs/advanced.html#%28part._htdp-advanced._.Numbers__.Integers__.Rationals__.Reals__.Complex__.Exacts__.Inexacts%29), it looks like even in Advanced, the `=` is supposed to have at least two arguments. 

Do you want this patch to apply only to Beginner? Confirm and I'll put the test in the right place(s).

**Comment by mfelleisen** [comment]
Indeed, it is customary to relax functions as we go up the hierarchy: so beginner-= should be in BSL and BSL+ L, and the relaxed version should be in ISL and up. Thanks!

**Comment by maueroats** [comment]
Only used in BSL now.

**Pull request merged**
